I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 444, in script
    k "Sure thing, Android remove Urth's core."
Exception: Sayer 'k' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 444, in script
    k "Sure thing, Android remove Urth's core."
  File "renpy/ast.py", line 680, in execute
    who = eval_who(self.who, self.who_fast)
  File "renpy/ast.py", line 574, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'k' is not defined.

Windows-10-10.0.19041
Ren'Py 7.4.4.1439
Tweleve 1.0
Tue Jun  8 16:30:08 2021
