I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 4, in script call
    call act1
  File "game/original_scripts/script-act1.rpy", line 7, in script call
    call showdoc (doc_1)
  File "game/documents.rpy", line 72, in script
    $ pause()
  File "game/documents.rpy", line 72, in <module>
    $ pause()
NameError: name 'pause' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 4, in script call
    call act1
  File "game/original_scripts/script-act1.rpy", line 7, in script call
    call showdoc (doc_1)
  File "game/documents.rpy", line 72, in script
    $ pause()
  File "renpy/ast.py", line 922, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "renpy/python.py", line 2218, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/documents.rpy", line 72, in <module>
    $ pause()
NameError: name 'pause' is not defined

Windows-10-10.0.19041
Ren'Py 7.4.4.1439
Tweleve 1.0
Wed Jun 23 18:14:19 2021
